name: Non-English Comments Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  non-english-comments-check:
    runs-on: ubuntu-latest

    env:
      # Directories to be excluded
      EXCLUDE_DIRS: ".git docs tests scripts assets node_modules build"
      # Files to be excluded
      EXCLUDE_FILES: "*.txt *.html *.css *.min.js *.mdx"

    steps:
      - uses: actions/checkout@v4

      - name: Search for Non-English comments
        run: |
          set -e
          # Define the regex pattern to match Chinese characters
          pattern='[\p{Han}]'

          # Process the directories to be excluded
          exclude_dirs=""
          for dir in $EXCLUDE_DIRS; do
            exclude_dirs="$exclude_dirs --exclude-dir=$dir"
          done

          # Process the file types to be excluded
          exclude_files=""
          for file in $EXCLUDE_FILES; do
            exclude_files="$exclude_files --exclude=$file"
          done

          # Use grep to find all comments containing Non-English characters
          # Check if the file contains '.md' and skip if it does
          grep -Pnr "$pattern" . $exclude_dirs $exclude_files | while read -r line ; do
            # If the filename contains '.md', skip it
            if echo "$line" | grep -q '\.md'; then
              continue
            fi
            # Write the result to the non_english_comments.txt file
            echo "$line" >> non_english_comments.txt
          done || true

      - name: Output non-English comments if found
        run: |
          if [ -s non_english_comments.txt ]; then
            echo "Non-English comments found in the following locations:"
            cat non_english_comments.txt
            exit 1  # terminate the workflow
          else
            echo "No Non-English comments found."
          fi

      # 如果在此处存在非英文注释，将会终止CI流程并报错
      # 里面会提示具体文件以及对应行数，方便快速定位